services:
  postgres:
    image: postgres:17.5 # Use an appropriate version of PostgreSQL
    environment:
      POSTGRES_USER: mortar
      POSTGRES_PASSWORD: mortar
      POSTGRES_DB: mortar
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mortar"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-migration:
    image: postgres:17.5 # Or any appropriate base image that has psql installed
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://mortar:mortar@postgres:5432/mortar
    entrypoint: >
      /bin/sh -c "
      until pg_isready -h postgres -p 5432; do echo waiting for db; sleep 2; done;
      psql $$DATABASE_URL -c 'CREATE TABLE IF NOT EXISTS bricks (
        id CHAR(36) PRIMARY KEY NOT NULL,
        name VARCHAR(255) NOT NULL UNIQUE,
        language VARCHAR(255) NOT NULL,
        source_path VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        last_invoked TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );'
      "

  mortar:
    image: mortar:latest
    depends_on:
      db-migration:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: postgres://mortar:mortar@postgres:5432/mortar
    ports:
      - "3333:3333"  # Expose port 3333 on the host to port 3333 in the container
    volumes:
      - ./bricks:/app/bricks
